# Generated by Django 5.2.7 on 2025-10-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_galeri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eskul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.URLField(blank=True)),
            ],
        ),
    ]
