# Generated by Django 5.2.7 on 2025-10-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_eskul'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurusan',
            name='jumlah_guru',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jurusan',
            name='jumlah_siswa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jurusan',
            name='nama_kaprog',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
